import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import { ThemeProvider } from "@/provider/theme-provider";
import { ShopProvider } from "@/context/ShopContext"; // Add this import
import { Toaster } from "sonner" 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ShopProvider> {/* Add ShopProvider here */}
            <Navbar />
            <main className="min-h-screen">{children}</main>
            <Footer />
             <Toaster richColors position="top-right" />
          </ShopProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}